#!/bin/bash
# Switch schema from SQLite (local dev) to PostgreSQL (Vercel).
# Run this AFTER you've created Vercel Postgres and pulled the env locally.
#
# Usage:  bash scripts/prepare-deploy.sh
#
# It will:
#   1. Swap the prisma datasource provider sqlite -> postgresql
#   2. Regenerate the initial migration with Postgres syntax
#   3. Leave the SQLite schema in scripts/schema.sqlite.prisma so you can switch back

set -euo pipefail
cd "$(dirname "$0")/.."

echo "▶ Backing up current SQLite schema → scripts/schema.sqlite.prisma"
cp prisma/schema.prisma scripts/schema.sqlite.prisma

echo "▶ Switching datasource to postgresql (Neon-compatible env var names)"
# Replace the sqlite block with postgres
cat > /tmp/pg_block.txt <<'EOF'
datasource db {
  provider  = "postgresql"
  url       = env("DATABASE_URL")
  directUrl = env("DATABASE_URL_UNPOOLED")
}
EOF

# Use python for cross-platform safe replace (sed -i is finicky on macOS vs Linux)
python3 <<'PYEOF'
from pathlib import Path
import re
p = Path("prisma/schema.prisma")
src = p.read_text()
pg_block = Path("/tmp/pg_block.txt").read_text().strip()
# Replace the datasource db { ... } block
src_new = re.sub(
    r"datasource db \{[^}]*\}",
    pg_block,
    src,
    count=1,
    flags=re.DOTALL,
)
p.write_text(src_new)
print("✓ Schema patched")
PYEOF

echo "▶ Regenerating Postgres migrations"
rm -rf prisma/migrations
mkdir -p prisma/migrations/0_init
npx prisma migrate diff --from-empty --to-schema-datamodel prisma/schema.prisma --script > prisma/migrations/0_init/migration.sql
cat > prisma/migrations/migration_lock.toml <<'EOF'
# Please do not edit this file manually
provider = "postgresql"
EOF

echo "▶ Regenerating Prisma client"
npx prisma generate

echo ""
echo "✅ Ready to deploy. Commit + push:"
echo ""
echo "    git add -A"
echo "    git commit -m 'Switch to PostgreSQL for production'"
echo "    git push"
echo ""
echo "After deploy, to switch BACK to SQLite for local dev:"
echo "    bash scripts/restore-sqlite.sh"
